baseURL = "https://example.com/"
title = "My Hugo Site"
theme = "hugo-arcana"

[params]
  logo = "images/logo.png"
  logoAlt = "My Logo"
  favicon = "images/favicon.png"
    [[params.social]]
        title = "Twitter"
        icon = "fa-twitter"
        url = "#"
    [[params.social]]
        title = "Facebook"
        icon = "fa-facebook-f"
        url = "#"
    [[params.social]]
        title = "GitHub"
        icon = "fa-github"
        url = "#"
    [[params.social]]
        title = "LinkedIn"
        icon = "fa-linkedin-in"
        url = "#"
    [[params.social]]
        title = "Creative Commons"
        icon = "fa-creative-commons"
        url = "https://creativecommons.org/"
