name: Deploy Hugo site to GitHub Pages

on:
  push:
    branches:
      - main # Trigger the workflow on pushes to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true  # Checkout any submodules, including the 'arcana' theme if used as one
          fetch-depth: 0    # Fetch all history for the gh-pages action

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true    # The arcana theme uses SCSS/Sass, so the extended version is necessary

      - name: Build Site
        run: hugo --minify --baseURL "https://Computacao-UABJ.github.io/computacao-uabj2.github.io/" # Replace with your actual baseURL

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main' # Only deploy if pushed to main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public             # The directory where Hugo builds the static files

